# This file generates the GitHub Actions matrix.
# Modified for Adafruit ItsyBitsy Dongle + Nice!Nano Halves

include:
  # ---------------------------------------------------------
  # 1. 接收器 Dongle (Adafruit ItsyBitsy nRF52840)
  # ---------------------------------------------------------
  - board: adafruit_itsybitsy_nrf52840
    # 注意：这里去掉了 dongle_display，因为 ItsyBitsy 引脚定义不同，
    # 强行加显示屏 shield 容易导致编译失败。
    shield: cygnus35_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: cygnus35_dongle_itsybitsy

  # ---------------------------------------------------------
  # 2. 左右手键盘 (Nice!Nano v2)
  # ---------------------------------------------------------
  - board: nice_nano_v2
    shield: cygnus35_ph_left
    artifact-name: cygnus35_ph_left

  - board: nice_nano_v2
    shield: cygnus35_right
    artifact-name: cygnus35_right

  # ---------------------------------------------------------
  # 3. 设置重置工具 (Settings Reset)
  # ---------------------------------------------------------
  # 用于 Nice!Nano 的重置
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_nicenano

  # 用于 ItsyBitsy 的重置 (新加项)
  - board: adafruit_itsybitsy_nrf52840
    shield: settings_reset
    artifact-name: settings_reset_itsybitsy
