# Modified config/build.yaml
# 修复: 根据日志列表，将板子名称从 nice_nano_v2 改为 nice_nano

include:
  # ---------------------------------------------------------
  # 1. 接收器 Dongle (实际硬件: Adafruit ItsyBitsy nRF52840)
  # ---------------------------------------------------------
  # 使用 nice_nano 代替 nice_nano_v2
  - board: nice_nano
    shield: cygnus35_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: cygnus35_dongle_itsybitsy_compatible

  # ---------------------------------------------------------
  # 2. 左右手键盘 (Nice!Nano)
  # ---------------------------------------------------------
  # 使用 nice_nano 代替 nice_nano_v2
  - board: nice_nano
    shield: cygnus35_ph_left
    artifact-name: cygnus35_ph_left

  - board: nice_nano
    shield: cygnus35_right
    artifact-name: cygnus35_right

  # ---------------------------------------------------------
  # 3. 设置重置工具 (Settings Reset)
  # ---------------------------------------------------------
  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset_universal
